"""SAP BTP REST client backed by a BTP destination service binding.

This module is generated by the migrate-agent-to-cf runbook. It encapsulates
all BTP platform API access through the BTP destination service. One Client
instance is created per BTP service destination (Accounts, Entitlements,
Resource Consumption, Metrics, Usage Records, Provisioning).

Required CF service binding (provided via VCAP_SERVICES):
* destination — exposes the destination-configuration REST API. Its service
                key already embeds an OAuth client (clientid, clientsecret,
                token endpoint url) used to fetch access tokens via the
                client_credentials grant — no separate xsuaa binding needed.

All BTP platform APIs are cloud-hosted REST services (no OData, no CSRF,
no on-premise connectivity required). Authentication is handled transparently
by the BTP destination service (OAuth2ClientCredentials flow).
"""

from __future__ import annotations

import json
import logging
import os
import time
from dataclasses import dataclass, field
from typing import Any

import httpx

logger = logging.getLogger(__name__)

# Each BTP service has its own destination name, read from env with fallback.
# Agent code overrides this per-client instance via the `destination_name` param.
DEFAULT_DESTINATION_NAME = os.environ.get("BTP_DESTINATION_NAME", "BTP_ACCOUNTS")
DEFAULT_TIMEOUT_SECONDS = float(os.environ.get("BTP_TIMEOUT_SECONDS", "20.0"))
TOKEN_TTL = float(os.environ.get("DESTINATION_TOKEN_TTL", "600"))
DEST_CACHE_TTL = float(os.environ.get("DESTINATION_CACHE_TTL", "300"))

RESPONSE_ENVELOPE = "rest"  # All BTP platform APIs return plain JSON (no OData envelope)
CSRF_REQUIRED = False        # BTP REST APIs do not require CSRF tokens


def _vcap() -> dict[str, Any]:
    raw = os.environ.get("VCAP_SERVICES")
    if not raw:
        return {}
    try:
        return json.loads(raw)
    except Exception:
        logger.warning("VCAP_SERVICES is set but not valid JSON")
        return {}


def _first_binding(label: str) -> dict[str, Any] | None:
    bindings = _vcap().get(label) or []
    if not bindings:
        return None
    return (bindings[0] or {}).get("credentials") or {}


@dataclass
class Destination:
    url: str
    auth_type: str
    username: str | None = None
    password: str | None = None
    sap_client: str | None = None
    proxy_type: str = "Internet"
    additional: dict[str, str] = field(default_factory=dict)
    bearer_token: str | None = None  # injected by Destination Service for OAuth2 types


@dataclass
class _CachedToken:
    value: str
    expires_at: float

    def expired(self) -> bool:
        return time.monotonic() >= self.expires_at


class _DestinationResolver:
    def __init__(self, timeout: float = DEFAULT_TIMEOUT_SECONDS) -> None:
        self._timeout = timeout
        self._xsuaa_token: _CachedToken | None = None
        self._dest_cache: dict[str, tuple[Destination, float]] = {}

    async def _client_credentials_token(
        self, token_url: str, client_id: str, client_secret: str
    ) -> str:
        async with httpx.AsyncClient(timeout=self._timeout) as client:
            r = await client.post(
                token_url.rstrip("/") + "/oauth/token",
                data={"grant_type": "client_credentials"},
                auth=(client_id, client_secret),
                headers={"Accept": "application/json"},
            )
        r.raise_for_status()
        return r.json()["access_token"]

    async def _xsuaa_access_token(self) -> str:
        if self._xsuaa_token and not self._xsuaa_token.expired():
            return self._xsuaa_token.value
        creds = _first_binding("destination") or {}
        if not creds:
            raise RuntimeError(
                "No 'destination' service binding found in VCAP_SERVICES. "
                "Bind a destination service instance to the app."
            )
        token = await self._client_credentials_token(
            creds["url"], creds["clientid"], creds["clientsecret"]
        )
        self._xsuaa_token = _CachedToken(token, time.monotonic() + TOKEN_TTL)
        return token

    async def resolve(self, name: str) -> Destination:
        cached = self._dest_cache.get(name)
        if cached and time.monotonic() < cached[1]:
            return cached[0]

        creds = _first_binding("destination") or {}
        if not creds:
            raise RuntimeError("No 'destination' service binding found in VCAP_SERVICES.")
        access_token = await self._xsuaa_access_token()
        uri = creds["uri"].rstrip("/")
        url = f"{uri}/destination-configuration/v1/destinations/{name}"
        async with httpx.AsyncClient(timeout=self._timeout) as client:
            r = await client.get(
                url,
                headers={
                    "Authorization": f"Bearer {access_token}",
                    "Accept": "application/json",
                },
            )
        if r.status_code >= 400:
            raise RuntimeError(
                f"Destination service returned {r.status_code} for '{name}': {r.text}"
            )
        body = r.json()
        cfg = body.get("destinationConfiguration") or {}
        d_url = (cfg.get("URL") or "").rstrip("/")
        if not d_url:
            raise RuntimeError(f"Destination '{name}' has no URL configured.")
        # Extract bearer token injected by Destination Service for OAuth2 destination types
        auth_tokens = body.get("authTokens") or []
        bearer_token: str | None = None
        if auth_tokens:
            first = auth_tokens[0]
            if not first.get("error"):
                bearer_token = first.get("value")
            else:
                logger.warning("Destination '%s' authTokens error: %s", name, first.get("error"))
        well_known = {
            "URL", "Name", "Type", "Authentication", "ProxyType",
            "User", "Password", "sap-client", "SAP-Client", "sap_client",
        }
        additional = {k: v for k, v in cfg.items() if k not in well_known}
        dest = Destination(
            url=d_url,
            auth_type=cfg.get("Authentication", "NoAuthentication"),
            username=cfg.get("User"),
            password=cfg.get("Password"),
            sap_client=None,  # BTP REST APIs do not use sap-client
            proxy_type=cfg.get("ProxyType", "Internet"),
            additional=additional,
            bearer_token=bearer_token,
        )
        self._dest_cache[name] = (dest, time.monotonic() + DEST_CACHE_TTL)
        return dest


class Client:
    """Async HTTP client for a single BTP platform API destination.

    Usage:
        client = Client(destination_name="BTP_ACCOUNTS")
        data = await client.get("/accounts/v1/subaccounts")
        data = await client.get("/accounts/v1/globalAccount", params={"expand": "true"})
    """

    def __init__(
        self,
        destination: Destination | None = None,
        destination_name: str = DEFAULT_DESTINATION_NAME,
        timeout: float = DEFAULT_TIMEOUT_SECONDS,
        resolver: _DestinationResolver | None = None,
    ) -> None:
        self._destination = destination
        self._destination_name = destination_name
        self._timeout = timeout
        self._resolver = resolver or _DestinationResolver(timeout=timeout)

    async def destination(self) -> Destination:
        if self._destination is None:
            self._destination = await self._resolver.resolve(self._destination_name)
        return self._destination

    def _build_url(self, base_url: str, service_path: str) -> str:
        if not service_path.startswith("/"):
            service_path = "/" + service_path
        return f"{base_url}{service_path}"

    def _auth(self, dest: Destination) -> httpx.BasicAuth | None:
        if dest.auth_type == "BasicAuthentication" and dest.username and dest.password:
            return httpx.BasicAuth(dest.username, dest.password)
        return None

    def _base_headers(self, dest: Destination, user_identity: str | None) -> dict[str, str]:
        h = {"Accept": "application/json"}
        if dest.bearer_token:
            h["Authorization"] = f"Bearer {dest.bearer_token}"
        if user_identity:
            h["X-User-Identity"] = user_identity
        return h

    def _unwrap_response(self, body: Any) -> Any:
        # RESPONSE_ENVELOPE == "rest": return raw JSON payload unchanged
        return body

    async def get(
        self,
        service_path: str,
        params: dict[str, Any] | None = None,
        user_identity: str | None = None,
    ) -> dict[str, Any]:
        dest = await self.destination()
        merged: dict[str, Any] = dict(params or {})
        headers = self._base_headers(dest, user_identity)
        async with httpx.AsyncClient(timeout=self._timeout) as client:
            r = await client.get(
                self._build_url(dest.url, service_path),
                auth=self._auth(dest),
                headers=headers,
                params=merged,
            )
        if r.status_code >= 400:
            return {
                "error": True,
                "status_code": r.status_code,
                "message": r.text,
                "url": self._build_url(dest.url, service_path),
            }
        try:
            body = r.json()
        except Exception:
            return {"error": True, "status_code": r.status_code, "message": r.text}
        return self._unwrap_response(body)

    async def post(
        self,
        service_path: str,
        body: dict[str, Any],
        service_root: str = "",
        user_identity: str | None = None,
    ) -> dict[str, Any]:
        dest = await self.destination()
        headers = self._base_headers(dest, user_identity)
        headers["Content-Type"] = "application/json"
        # CSRF_REQUIRED = False for all BTP REST APIs — no CSRF fetch needed
        async with httpx.AsyncClient(timeout=self._timeout) as client:
            r = await client.post(
                self._build_url(dest.url, service_path),
                json=body,
                auth=self._auth(dest),
                headers=headers,
            )
        if r.status_code >= 400:
            return {"error": True, "status_code": r.status_code, "message": r.text}
        try:
            return r.json()
        except Exception:
            return {"status_code": r.status_code, "raw": r.text}


__all__ = ["Client", "Destination", "DEFAULT_DESTINATION_NAME", "_DestinationResolver", "_first_binding"]
